#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt update
sudo apt install nginx
sudo nano /etc/nginx/nginx.conf
http {
    # ...
    server_tokens off;  # Optional: Hide Nginx version in response header
    
    # Set custom HTTP header
    add_header X-Served-By $hostname;
}
sudo service nginx restart
