#!/usr/bin/env bash
# This script replaces the word 'enabled' wit 'available' in
# ../sites-enabled/default to enable nginx to listen to port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
